/**
 * Taxonomy of Cognitive Insights
 * Defines the strict categorizations for all insights generated by the Insight Engine.
 */
export type TaxonomyDomain =
  | 'Learning'      // Knowledge acquisition markers
  | 'Automaticity'  // Skill mastery phase transitions
  | 'Gap'           // Cognitive load vulnerabilities
  | 'Prompting'     // Prompt engineering habits
  | 'Writing'       // Linguistic and structural composition
  | 'Reasoning'     // Logical framing and analytical depth
  | 'Identity';     // Core user preferences and traits

export interface InsightCandidate {
  readonly id: string;
  readonly domain: TaxonomyDomain;
  readonly title: string;
  readonly summary: string;
  readonly confidence: number; // 0.0 to 1.0
  readonly evidenceCount: number;
  readonly metadata: Record<string, unknown>;
}

export type SkillPhase = 'Cognitive' | 'Associative' | 'Autonomous';

export interface AutomaticityState {
  readonly skillName: string;
  readonly currentPhase: SkillPhase;
  readonly stabilityScore: number;
  readonly sessionCount: number;
}
