/**
 * v0.2 calibration: continuous half-life decay replaces the v0.1 3-tier step
 * function (100% under 30d / 50% 30-90d / 10% over 90d). The step function had
 * a hard discontinuity at each cliff — evidence from day 29 counted double
 * evidence from day 31, and evidence from day 89 counted 5x evidence from day
 * 91, for no principled reason. `weight = 0.5 ^ (age / HALF_LIFE_MS)` is
 * calibrated so `HALF_LIFE_MS` reproduces the old 30-day midpoint exactly
 * (weight(30d) = 0.5) while landing close to the old 90-day reference point
 * (weight(90d) = 0.125 vs. the old 0.1) — same reference points, no cliffs.
 * `MIN_EVIDENCE_WEIGHT` preserves the v0.1 property that evidence never fully
 * expires (old code floored at a permanent 10% weight past 90 days) — pure
 * exponential decay would otherwise fade very old evidence to ~0, silently
 * dropping a design intent the step function had. See
 * docs/research/confidence-calibration.md for the full comparison and
 * alternatives considered (kept step function, linear decay, no floor).
 */
const HALF_LIFE_MS = 30 * 24 * 60 * 60 * 1000;
const MIN_EVIDENCE_WEIGHT = 0.1;

export class ConfidenceCalculator {
  /**
   * Calculates the confidence of a potential insight based on the evidence events.
   * @param evidence Array of event timestamps (in ms) that support the insight.
   * @param requiredEvidenceCount The threshold number of events required for a baseline 1.0 score.
   * @param baselineStrategyScore The base confidence generated by the strategy (0.0 to 1.0).
   * @param contradictsExistingIdentity Boolean indicating if this insight contradicts established identity.
   * @param existingEvidenceCount If contradicting, how much evidence the old identity had.
   * @param now Current timestamp (for testing/decay calculation).
   * @returns A confidence score between 0.0 and 1.0.
   */
  public calculate(
    evidence: number[],
    requiredEvidenceCount: number,
    baselineStrategyScore: number,
    contradictsExistingIdentity: boolean = false,
    existingEvidenceCount: number = 0,
    now: number = Date.now()
  ): number {
    if (evidence.length === 0) return 0;

    let weightedEvidenceCount = 0;

    for (const timestamp of evidence) {
      const age = Math.max(now - timestamp, 0);
      weightedEvidenceCount += Math.max(Math.pow(0.5, age / HALF_LIFE_MS), MIN_EVIDENCE_WEIGHT);
    }

    // Base confidence based on evidence volume vs threshold
    const volumeMultiplier = Math.min(weightedEvidenceCount / requiredEvidenceCount, 1.0);
    let confidence = volumeMultiplier * baselineStrategyScore;

    // Contradiction Penalty
    if (contradictsExistingIdentity) {
      // If the new evidence is 2x the old evidence, we don't penalize.
      // Otherwise, slash confidence by 40%.
      if (weightedEvidenceCount < existingEvidenceCount * 2) {
        confidence *= 0.6; 
      }
    }

    return Math.max(0, Math.min(1, confidence));
  }
}
