export class ConfidenceCalculator {
  // 30 days in ms
  private static readonly DECAY_30_DAYS = 30 * 24 * 60 * 60 * 1000;
  // 90 days in ms
  private static readonly DECAY_90_DAYS = 90 * 24 * 60 * 60 * 1000;

  /**
   * Calculates the confidence of a potential insight based on the evidence events.
   * @param evidence Array of event timestamps (in ms) that support the insight.
   * @param requiredEvidenceCount The threshold number of events required for a baseline 1.0 score.
   * @param baselineStrategyScore The base confidence generated by the strategy (0.0 to 1.0).
   * @param contradictsExistingIdentity Boolean indicating if this insight contradicts established identity.
   * @param existingEvidenceCount If contradicting, how much evidence the old identity had.
   * @param now Current timestamp (for testing/decay calculation).
   * @returns A confidence score between 0.0 and 1.0.
   */
  public calculate(
    evidence: number[],
    requiredEvidenceCount: number,
    baselineStrategyScore: number,
    contradictsExistingIdentity: boolean = false,
    existingEvidenceCount: number = 0,
    now: number = Date.now()
  ): number {
    if (evidence.length === 0) return 0;

    let weightedEvidenceCount = 0;

    for (const timestamp of evidence) {
      const age = now - timestamp;
      if (age > ConfidenceCalculator.DECAY_90_DAYS) {
        weightedEvidenceCount += 0.1; // 10% weight
      } else if (age > ConfidenceCalculator.DECAY_30_DAYS) {
        weightedEvidenceCount += 0.5; // 50% weight
      } else {
        weightedEvidenceCount += 1.0; // 100% weight
      }
    }

    // Base confidence based on evidence volume vs threshold
    const volumeMultiplier = Math.min(weightedEvidenceCount / requiredEvidenceCount, 1.0);
    let confidence = volumeMultiplier * baselineStrategyScore;

    // Contradiction Penalty
    if (contradictsExistingIdentity) {
      // If the new evidence is 2x the old evidence, we don't penalize.
      // Otherwise, slash confidence by 40%.
      if (weightedEvidenceCount < existingEvidenceCount * 2) {
        confidence *= 0.6; 
      }
    }

    return Math.max(0, Math.min(1, confidence));
  }
}
